; Generated by py2c64 compiler
; --- Python Source Code ---
; x1 = 10
; x2 = 20
; z = x1 + x2
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; a1 = 5
; b = 3
; c = a1 * b + (a1 - b) // 2
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; x1 = 250
; x2 = 10
; z = x1 + x2
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; x1 = 10
; x2 = 0
; z = x1 // x2
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; a = 10 # 00001010
; b = 5  # 00000101
; c = a ^ b # Expected result: 15 (00001111)
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; val1 = 255 # 11111111 00000000
; val2 = 85  # 01010101 00000000
; # 255 (00FF) ^ 85 (0055) = 170 (00AA)
; res_xor = val1 ^ val2
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; x = 2 * 5
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; y = 10 // 0
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; z = 5 + 3.14
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; my_list = [1, 2, 3]
; for item in my_list:
;   x = item * 2
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; i = 0
; while i < 5:
;   i = i + 1
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; x = 10
; res = 0
; if x == 10:
;   res = 1
; # Expected: res = 1
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
; Generated by py2c64 compiler
; --- Python Source Code ---
; x = 5
; res = 0
; if x == 10:
;   res = 1
; # Expected: res = 0
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
; Generated by py2c64 compiler
; --- Python Source Code ---
; x = 10
; res = 0
; if x > 5:
;   res = 1
; else:
;   res = 2
; # Expected: res = 1
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
; Generated by py2c64 compiler
; --- Python Source Code ---
; x = 3
; res = 0
; if x > 5:
;   res = 1
; else:
;   res = 2
; # Expected: res = 2
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
; Generated by py2c64 compiler
; --- Python Source Code ---
; x = 15
; res = 0
; if x > 10:
;   res = 1
; elif x > 5:
;   res = 2
; else:
;   res = 3
; # Expected: res = 1
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
; Generated by py2c64 compiler
; --- Python Source Code ---
; x = 7
; res = 0
; if x > 10:
;   res = 1
; elif x > 5:
;   res = 2
; else:
;   res = 3
; # Expected: res = 2
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
; Generated by py2c64 compiler
; --- Python Source Code ---
; x = 3
; res = 0
; if x > 10:
;   res = 1
; elif x > 5:
;   res = 2
; else:
;   res = 3
; # Expected: res = 3
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
; Generated by py2c64 compiler
; --- Python Source Code ---
; x = 12
; res = 0
; if x > 10:
;   res = 1
; elif x > 5:
;   res = 2
; # Expected: res = 1
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
; Generated by py2c64 compiler
; --- Python Source Code ---
; x = 8
; res = 0
; if x > 10:
;   res = 1
; elif x > 5:
;   res = 2
; # Expected: res = 2
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
; Generated by py2c64 compiler
; --- Python Source Code ---
; x = 5
; y = 5
; res = 0
; if x <= y:
;   res = 1
; # Expected: res = 1
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
; Generated by py2c64 compiler
; --- Python Source Code ---
; x = 5
; y = 5
; res = 0
; if x < y:
;   res = 1
; # Expected: res = 0
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
; Generated by py2c64 compiler
; --- Python Source Code ---
; x = 10
; y = 5
; res = 0
; if x > 5:
;   if y < 10:
;     res = 1
;   else:
;     res = 2
; else:
;   res = 3
; # Expected: res = 1
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
; Generated by py2c64 compiler
; --- Python Source Code ---
; res = 0
; if True:
;   res = 1
; # Expected: res = 1
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; res = 0
; if False:
;   res = 1
; else:
;   res = 2
; # Expected: res = 2
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; x = 5
; y = 10
; res = 0
; if x + 2 > y - 5:
;   res = 1
; # Expected: 7 > 5 -> res = 1
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
; Generated by py2c64 compiler
; --- Python Source Code ---
; x = 3
; y = 1
; res = 0
; if x * 2 == y + 5:
;   res = 1
; # Expected: 6 == 6 -> res = 1
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
; Generated by py2c64 compiler
; --- Python Source Code ---
; x = 0
; res = 0
; if not x:
;   res = 1
; # Expected: not 0 -> True -> res = 1
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
; Generated by py2c64 compiler
; --- Python Source Code ---
; x = 5
; res = 0
; if not x:
;   res = 1
; # Expected: not 5 -> False -> res = 0
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
; Generated by py2c64 compiler
; --- Python Source Code ---
; x = 5
; y = 10
; res = 0
; if x > 0 and y > 0:
;   res = 1
; # Expected: True and True -> res = 1
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; x = 5
; y = 0
; res = 0
; if x > 0 and y > 0:
;   res = 1
; # Expected: True and False -> res = 0
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; x = 0
; y = 10
; res = 0
; if x > 0 and y > 0: # y > 0 should not be evaluated if the compiler is smart
;   res = 1
; # Expected: False and True -> res = 0
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; x = 5
; y = 0
; res = 0
; if x > 0 or y > 0: # y > 0 should not be evaluated
;   res = 1
; # Expected: True or False -> res = 1
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; x = 0
; y = 10
; res = 0
; if x > 0 or y > 0:
;   res = 1
; # Expected: False or True -> res = 1
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; x = 0
; y = 0
; res = 0
; if x > 0 or y > 0:
;   res = 1
; # Expected: False or False -> res = 0
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; x = 5
; y = 0
; res = 0
; if not (x == 0 and y == 0):
;   res = 1
; # Expected: not (False and True) -> not False -> True -> res = 1
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
; Generated by py2c64 compiler
; --- Python Source Code ---
; x = 0
; y = 0
; res = 0
; if not (x > 0 or y > 0):
;   res = 1
; # Expected: not (False or False) -> not False -> True -> res = 1
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
; Generated by py2c64 compiler
; --- Python Source Code ---
; res = 0
; if True and False:
;   res = 1
; # Expected: res = 0
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; a = 10
; b = 5
; res = 0
; if (a ^ b): # 10^5 = 15 (non-zero, quindi True)
;   res = 1
; # Expected: res = 1
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; a = 7
; b = 7
; res = 0
; if (a ^ b): # 7^7 = 0 (zero, quindi False)
;   res = 1
; # Expected: res = 0
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; i = 0
; res = 0
; while i < 10:
;   res = res + i
;   i = i + 1
;   if i == 5:
;     break
; # Expected: res = 0+1+2+3+4 = 10, i = 5
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; i = 0
; res = 0
; while i < 5:
;   i = i + 1
;   if i == 3:
;     continue
;   res = res + i
; # Expected: i=5, res = 1+2+4+5 = 12
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; my_list = [1, 2, 3, 4, 5]
; res = 0
; for item in my_list:
;   if item == 4:
;     break
;   res = res + item
; # Expected: res = 1+2+3 = 6
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; my_list = [1, 2, 3, 4, 5]
; res = 0
; for item in my_list:
;   if item == 3:
;     continue
;   res = res + item
; # Expected: res = 1+2+4+5 = 12
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; outer_sum = 0
; my_list = [1, 2, 3]
; for x in my_list: # x = 1, 2, 3
;     outer_sum = outer_sum + x
;     y = 0
;     while y < 2: # y = 0, 1
;         y = y + 1 # In Python, this would be inside the loop
;         if x == 2:
;             break # Exits the inner while if x is 2
;     # Se x=1, y arriva a 2. outer_sum = 1
;     # Se x=2, y=1, break. outer_sum = 1+2=3
;     # Se x=3, y arriva a 2. outer_sum = 3+3=6
; # Expected: outer_sum = 6
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; my_dict = {}
; my_dict['c'] = 3
; del my_dict['d']
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; my_dict = {'a': 1, 'b': 2}
; x1 = my_dict['a']
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; t = (1, 2, 3)
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; s = {1, 2, 3, 2, 1}
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; a_int = 10
; b_float_literal = 1.5
; c_float_result = a_int + b_float_literal
; # To observe the result, you might add: print(c_float_result)
; # For now, we primarily verify the generated assembly for the calculation.
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; a_float = 3.14
; b_float = 2.71
; result = a_float < b_float
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; x_float = 1.5
; y_float = 1.5
; is_equal = x_float == y_float
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; p_float = 10.0
; q_float = 10.000001
; is_not_equal = p_float != q_float
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; int_val = 5
; float_val = 4.99
; is_greater = int_val > float_val
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; x = 3.5
; y = -0.25
; z = 0.0
; # Verification of byte patterns for x, y, z in the .asm data section
; # would be done by inspecting the generated expected_outputs/float_assignments_literals/assign_positive_float_literal.asm
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; a = -5.25
; abs_a = abs(a)  # Expected: 5.25
; b = 0.0
; sgn_a = sgn(a)    # Expected: -1.0
; sgn_b = sgn(b)    # Expected: 0.0
; sgn_c = sgn(10.0) # Expected: 1.0
; d = 2.0 # Placeholder for log, as FP_LOG is a stub
; log_d = log(d)
; log_int = log(1) # Test coercion
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
jsr integer_abs
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; # Test exp() stub - should call FP_EXP and handle type.
; # FP_EXP itself will signal NotImplementedError at runtime.
; # We are testing the compilation path to FP_EXP.
; res_exp_float = exp(1.0)
; res_exp_int = exp(2) # Test integer to float coercion for argument
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; a = 3.5
; b = 3.5
; c = -2.0
; 
; res_eq = (a == b)  # Expected: True (1)
; res_ne = (a != c)  # Expected: True (1)
; res_lt = (c < a)   # Expected: True (1)
; res_gt = (a > c)   # Expected: True (1)
; res_le1 = (a <= b) # Expected: True (1)
; res_le2 = (c <= a) # Expected: True (1)
; res_ge1 = (a >= b) # Expected: True (1)
; res_ge2 = (a >= c) # Expected: True (1)
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; a_int = 5
; b_float = float(a_int)
; 
; c_float = -3.75
; d_int = int(c_float)
; 
; # Expected (for verification via print or debugger if available):
; # b_float should be 5.0
; # d_int should be -3 (due to truncation towards zero)
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
jsr convert_to_float
jsr convert_to_int
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; def get_pi():
;     return 3.14
; 
; a = get_pi()
; # 'a' should be treated as a float (4 bytes copied from __func_retval)
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:

func_get_pi_0:
    ; --- Function Prologue for get_pi ---
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR push_word_from_addr
    LDA $E0
    STA $E2
    LDA $E1
    STA $E3
    ; --- End Function Prologue ---
    JMP func_get_pi_ret_0

func_get_pi_ret_0:
    ; --- Function Epilogue for get_pi ---
    LDA $E2
    STA $E0
    LDA $E3
    STA $E1
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR pop_word_to_addr
    RTS
    ; --- End Function Epilogue ---
    JSR func_get_pi_0
    LDA $F8
    STA a+3
    LDA $F9
    STA a+0
    LDA $FA
    STA a+1
    LDA $FB
    STA a+2
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; def to_float(x):
;     y = 1 # dummy local var
;     return float(x)
; 
; b_val = 10
; b = to_float(b_val)
; # 'b' should be treated as a float (4 bytes copied)
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:

func_to_float_0:
    ; --- Function Prologue for to_float ---
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR push_word_from_addr
    LDA $E0
    STA $E2
    LDA $E1
    STA $E3
    ; --- End Function Prologue ---
    JMP func_to_float_ret_0

func_to_float_ret_0:
    ; --- Function Epilogue for to_float ---
    LDA $E2
    STA $E0
    LDA $E3
    STA $E1
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR pop_word_to_addr
    RTS
    ; --- End Function Epilogue ---
    JSR func_to_float_0
    LDA $F8
    STA b+3
    LDA $F9
    STA b+0
    LDA $FA
    STA b+1
    LDA $FB
    STA b+2
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; def get_int():
;     return 100
; 
; c = get_int()
; # 'c' should be treated as an int (2 bytes copied)
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:

func_get_int_0:
    ; --- Function Prologue for get_int ---
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR push_word_from_addr
    LDA $E0
    STA $E2
    LDA $E1
    STA $E3
    ; --- End Function Prologue ---
    JMP func_get_int_ret_0

func_get_int_ret_0:
    ; --- Function Epilogue for get_int ---
    LDA $E2
    STA $E0
    LDA $E3
    STA $E1
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR pop_word_to_addr
    RTS
    ; --- End Function Epilogue ---
    JSR func_get_int_0
    STX c
    STA c+1
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; def returns_float():
;     val = 0.0 # dummy local
;     val = 1.5
;     return val # Current analysis might not catch this if 'val' type isn't tracked well
; 
; def returns_float_direct():
;     return 1.5
; 
; def returns_int():
;     return 7
; 
; f_val = returns_float_direct() # This should be detected as float return
; i_val = returns_int()
; # f_val is float, i_val is int
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:

func_returns_float_0:
    ; --- Function Prologue for returns_float ---
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR push_word_from_addr
    LDA $E0
    STA $E2
    LDA $E1
    STA $E3
    ; --- End Function Prologue ---
    JMP func_returns_float_ret_0

func_returns_float_ret_0:
    ; --- Function Epilogue for returns_float ---
    LDA $E2
    STA $E0
    LDA $E3
    STA $E1
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR pop_word_to_addr
    RTS
    ; --- End Function Epilogue ---

func_returns_float_direct_1:
    ; --- Function Prologue for returns_float_direct ---
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR push_word_from_addr
    LDA $E0
    STA $E2
    LDA $E1
    STA $E3
    ; --- End Function Prologue ---
    JMP func_returns_float_direct_ret_1

func_returns_float_direct_ret_1:
    ; --- Function Epilogue for returns_float_direct ---
    LDA $E2
    STA $E0
    LDA $E3
    STA $E1
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR pop_word_to_addr
    RTS
    ; --- End Function Epilogue ---

func_returns_int_2:
    ; --- Function Prologue for returns_int ---
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR push_word_from_addr
    LDA $E0
    STA $E2
    LDA $E1
    STA $E3
    ; --- End Function Prologue ---
    JMP func_returns_int_ret_2

func_returns_int_ret_2:
    ; --- Function Epilogue for returns_int ---
    LDA $E2
    STA $E0
    LDA $E3
    STA $E1
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR pop_word_to_addr
    RTS
    ; --- End Function Epilogue ---
    JSR func_returns_float_direct_1
    LDA $F8
    STA f_val+3
    LDA $F9
    STA f_val+0
    LDA $FA
    STA f_val+1
    LDA $FB
    STA f_val+2
    JSR func_returns_int_2
    STX i_val
    STA i_val+1
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; res = 0
; def my_func():
;   global res
;   res = 10
; my_func()
; # Expected: res = 10
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:

func_my_func_0:
    ; --- Function Prologue for my_func ---
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR push_word_from_addr
    LDA $E0
    STA $E2
    LDA $E1
    STA $E3
    ; --- End Function Prologue ---

func_my_func_ret_0:
    ; --- Function Epilogue for my_func ---
    LDA $E2
    STA $E0
    LDA $E3
    STA $E1
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR pop_word_to_addr
    RTS
    ; --- End Function Epilogue ---
    ; --- Preparazione chiamata a my_func ---
    JSR func_my_func_0
    ; --- Fine chiamata a my_func (valore di ritorno in A/X scartato) ---
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; def add_one(x):
;   return x + 1
; val = 5
; result = add_one(val)
; # Expected: result = 6
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:

func_add_one_0:
    ; --- Function Prologue for add_one ---
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR push_word_from_addr
    LDA $E0
    STA $E2
    LDA $E1
    STA $E3
    ; --- End Function Prologue ---
    JMP func_add_one_ret_0

func_add_one_ret_0:
    ; --- Function Epilogue for add_one ---
    LDA $E2
    STA $E0
    LDA $E3
    STA $E1
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR pop_word_to_addr
    RTS
    ; --- End Function Epilogue ---
    JSR func_add_one_0
    STX result
    STA result+1
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; def multiply(a, b):
;   return a * b
; res = multiply(3, 4)
; # Expected: res = 12
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:

func_multiply_0:
    ; --- Function Prologue for multiply ---
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR push_word_from_addr
    LDA $E0
    STA $E2
    LDA $E1
    STA $E3
    ; --- End Function Prologue ---
    JMP func_multiply_ret_0

func_multiply_ret_0:
    ; --- Function Epilogue for multiply ---
    LDA $E2
    STA $E0
    LDA $E3
    STA $E1
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR pop_word_to_addr
    RTS
    ; --- End Function Epilogue ---
    JSR func_multiply_0
    STX res
    STA res+1
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; def set_val_to_zero():
;   return
; x = 5
; x = set_val_to_zero()
; # Expected: x = 0
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:

func_set_val_to_zero_0:
    ; --- Function Prologue for set_val_to_zero ---
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR push_word_from_addr
    LDA $E0
    STA $E2
    LDA $E1
    STA $E3
    ; --- End Function Prologue ---
    LDA #0
    LDX #0
    JMP func_set_val_to_zero_ret_0

func_set_val_to_zero_ret_0:
    ; --- Function Epilogue for set_val_to_zero ---
    LDA $E2
    STA $E0
    LDA $E3
    STA $E1
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR pop_word_to_addr
    RTS
    ; --- End Function Epilogue ---
    JSR func_set_val_to_zero_0
    STX x
    STA x+1
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; y = 0
; def do_nothing(p):
;   y = p + 1 # Modifica una globale per vedere se viene eseguita
; val = 0
; val = do_nothing(5)
; # Expected: val = 0, y = 6 (y non è il return value)
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:

func_do_nothing_0:
    ; --- Function Prologue for do_nothing ---
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR push_word_from_addr
    LDA $E0
    STA $E2
    LDA $E1
    STA $E3
    ; --- End Function Prologue ---

func_do_nothing_ret_0:
    ; --- Function Epilogue for do_nothing ---
    LDA $E2
    STA $E0
    LDA $E3
    STA $E1
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR pop_word_to_addr
    RTS
    ; --- End Function Epilogue ---
    JSR func_do_nothing_0
    STX val
    STA val+1
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; def identity(n):
;   return n
; result = identity(100)
; # Expected: result = 100
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:

func_identity_0:
    ; --- Function Prologue for identity ---
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR push_word_from_addr
    LDA $E0
    STA $E2
    LDA $E1
    STA $E3
    ; --- End Function Prologue ---
    JMP func_identity_ret_0

func_identity_ret_0:
    ; --- Function Epilogue for identity ---
    LDA $E2
    STA $E0
    LDA $E3
    STA $E1
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR pop_word_to_addr
    RTS
    ; --- End Function Epilogue ---
    JSR func_identity_0
    STX result
    STA result+1
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; def square(val):
;   return val * val
; a = 2
; b = 3
; # Chiamata: square( (a+b) ) -> square(5)
; result = square(a + b)
; # Expected: result = 25
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:

func_square_0:
    ; --- Function Prologue for square ---
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR push_word_from_addr
    LDA $E0
    STA $E2
    LDA $E1
    STA $E3
    ; --- End Function Prologue ---
    JMP func_square_ret_0

func_square_ret_0:
    ; --- Function Epilogue for square ---
    LDA $E2
    STA $E0
    LDA $E3
    STA $E1
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR pop_word_to_addr
    RTS
    ; --- End Function Epilogue ---
    JSR func_square_0
    STX result
    STA result+1
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; def inner_func(val):
;   return val * 2
; def outer_func(x):
;   return inner_func(x + 1)
; # Chiamata: outer_func(3) -> inner_func(4) -> 8
; result = outer_func(3)
; # Expected: result = 8
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:

func_inner_func_0:
    ; --- Function Prologue for inner_func ---
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR push_word_from_addr
    LDA $E0
    STA $E2
    LDA $E1
    STA $E3
    ; --- End Function Prologue ---
    JMP func_inner_func_ret_0

func_inner_func_ret_0:
    ; --- Function Epilogue for inner_func ---
    LDA $E2
    STA $E0
    LDA $E3
    STA $E1
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR pop_word_to_addr
    RTS
    ; --- End Function Epilogue ---

func_outer_func_1:
    ; --- Function Prologue for outer_func ---
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR push_word_from_addr
    LDA $E0
    STA $E2
    LDA $E1
    STA $E3
    ; --- End Function Prologue ---
    JSR func_inner_func_0
    STX temp_0
    STA temp_0+1
    JMP func_outer_func_ret_1

func_outer_func_ret_1:
    ; --- Function Epilogue for outer_func ---
    LDA $E2
    STA $E0
    LDA $E3
    STA $E1
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR pop_word_to_addr
    RTS
    ; --- End Function Epilogue ---
    JSR func_outer_func_1
    STX result
    STA result+1
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; def check_sign(num):
;   if num > 0:
;     return 1
;   elif num < 0:
;     return -1
;   else:
;     return 0
; res_pos = check_sign(10)
; res_neg = check_sign(-5)
; res_zero = check_sign(0)
; # Expected: res_pos = 1, res_neg = -1, res_zero = 0
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:

func_check_sign_0:
    ; --- Function Prologue for check_sign ---
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR push_word_from_addr
    LDA $E0
    STA $E2
    LDA $E1
    STA $E3
    ; --- End Function Prologue ---
; Generated by py2c64 compiler
; --- Python Source Code ---
; glob_var = 50
; def modify_global():
;   global glob_var
;   glob_var = 100
; modify_global()
; # Expected: glob_var = 100
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:

func_modify_global_0:
    ; --- Function Prologue for modify_global ---
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR push_word_from_addr
    LDA $E0
    STA $E2
    LDA $E1
    STA $E3
    ; --- End Function Prologue ---

func_modify_global_ret_0:
    ; --- Function Epilogue for modify_global ---
    LDA $E2
    STA $E0
    LDA $E3
    STA $E1
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR pop_word_to_addr
    RTS
    ; --- End Function Epilogue ---
    ; --- Preparazione chiamata a modify_global ---
    JSR func_modify_global_0
    ; --- Fine chiamata a modify_global (valore di ritorno in A/X scartato) ---
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; x = 10 # Globale
; def func_with_collision(x): # Parametro x
;   return x * 2 # Dovrebbe usare il parametro x
; # Chiamata: func_with_collision(5) -> 10. La x globale rimane 10.
; result = func_with_collision(5)
; # Expected: result = 10, x (globale) = 10
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:

func_func_with_collision_0:
    ; --- Function Prologue for func_with_collision ---
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR push_word_from_addr
    LDA $E0
    STA $E2
    LDA $E1
    STA $E3
    ; --- End Function Prologue ---
    JMP func_func_with_collision_ret_0

func_func_with_collision_ret_0:
    ; --- Function Epilogue for func_with_collision ---
    LDA $E2
    STA $E0
    LDA $E3
    STA $E1
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR pop_word_to_addr
    RTS
    ; --- End Function Epilogue ---
    JSR func_func_with_collision_0
    STX result
    STA result+1
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; def subtract(a, b):
;   return a - b
; var1 = 10
; var2 = 3
; result = subtract(var1, var2)
; # Expected: result = 7
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:

func_subtract_0:
    ; --- Function Prologue for subtract ---
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR push_word_from_addr
    LDA $E0
    STA $E2
    LDA $E1
    STA $E3
    ; --- End Function Prologue ---
    JMP func_subtract_ret_0

func_subtract_ret_0:
    ; --- Function Epilogue for subtract ---
    LDA $E2
    STA $E0
    LDA $E3
    STA $E1
    LDA #<00E2
    STA $F2
    LDA #>00E2
    STA $F3
    JSR pop_word_to_addr
    RTS
    ; --- End Function Epilogue ---
    JSR func_subtract_0
    STX result
    STA result+1
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; gfx_turn_on()
; gfx_clear_screen()
; while True: # pragma: no cover
;     pass # pragma: no cover
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
    jsr gfx_turn_on
    jsr gfx_clear_screen
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; gfx_turn_on()
; gfx_clear_screen()
; 
; # Draw the lines that form the star
; draw_line(160, 100, 240, 40)
; draw_line(240, 40, 260, 120)
; draw_line(260, 120, 160, 160)
; draw_line(160, 160, 60, 120)
; draw_line(60, 120, 80, 40)
; draw_line(80, 40, 160, 100)
; 
; # Loop forever to keep the image on screen
; while True: # pragma: no cover
;     pass # pragma: no cover
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
    jsr gfx_turn_on
    jsr gfx_clear_screen
    sta $fb
    stx $fc
    sta $fd
    jsr gfx_draw_line
    sta $fb
    stx $fc
    sta $fd
    jsr gfx_draw_line
    sta $fb
    stx $fc
    sta $fd
    jsr gfx_draw_line
    sta $fb
    stx $fc
    sta $fd
    jsr gfx_draw_line
    sta $fb
    stx $fc
    sta $fd
    jsr gfx_draw_line
    sta $fb
    stx $fc
    sta $fd
    jsr gfx_draw_line
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; gfx_turn_on()
; gfx_turn_off()
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
    jsr gfx_turn_on
    jsr gfx_turn_off
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; gfx_turn_on()
; gfx_clear_screen()
; 
; # Draw an ellipse
; draw_ellipse(160, 100, 80, 40)
; 
; # Draw a circle (ellipse with equal radii)
; draw_ellipse(60, 150, 30, 30)
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
    jsr gfx_turn_on
    jsr gfx_clear_screen
    sta $fb
    stx $fc
    sta $fd
    jsr gfx_draw_ellipse
    sta $fb
    stx $fc
    sta $fd
    jsr gfx_draw_ellipse
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; gfx_turn_on()
; gfx_clear_screen()
; # Disegna un cerchio con valori costanti
; draw_circle(120, 90, 40)
; while True: # pragma: no cover
;     pass # pragma: no cover
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
    jsr gfx_turn_on
    jsr gfx_clear_screen
    sta $fb
    stx $fc
    sta $fd
    jsr gfx_draw_circle
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; gfx_turn_on()
; gfx_clear_screen()
; # Disegna un cerchio usando variabili
; x_center = 200
; y_center = 110
; radius = 60
; draw_circle(x_center, y_center, radius)
; while True: # pragma: no cover
;     pass # pragma: no cover
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
    jsr gfx_turn_on
    jsr gfx_clear_screen
    sta $fb
    stx $fc
    sta $fd
    jsr gfx_draw_circle
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; gfx_turn_on()
; gfx_clear_screen()
; # Disegna un'ellisse usando espressioni come argomenti
; offset_x = 10
; offset_y = 5
; draw_ellipse(160 + offset_x, 100 - offset_y, 40 * 2, 60 // 2)
; while True: # pragma: no cover
;     pass # pragma: no cover
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
    jsr gfx_turn_on
    jsr gfx_clear_screen
    sta $fb
    stx $fc
    sta $fd
    jsr gfx_draw_ellipse
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; gfx_turn_on()
; gfx_clear_screen()
; # Disegna un rettangolo con valori costanti
; draw_rect(50, 50, 270, 150)
; while True: # pragma: no cover
;     pass # pragma: no cover
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
    jsr gfx_turn_on
    jsr gfx_clear_screen
    sta $fb
    stx $fc
    sta $fd
    jsr gfx_draw_rect
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; # Imposta la posizione dello sprite 0 a (150, 100) usando variabili
; sprite_num = 0
; x_pos = 150
; y_pos = 100
; sprite_set_pos(sprite_num, x_pos, y_pos)
; 
; # Imposta la posizione dello sprite 1 a (180, 120) con costanti
; sprite_set_pos(1, 180, 120)
; 
; while True: # pragma: no cover
;     pass # pragma: no cover
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
    jsr sprite_set_pos
    jsr sprite_set_pos
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; # Abilita sprite 0 e 2 (maschera 1+4=5)
; sprite_enable(5)
; 
; # Imposta il colore dello sprite 0 a blu (6)
; sprite_num = 0
; color_code = 6
; sprite_set_color(sprite_num, color_code)
; 
; # Imposta il colore dello sprite 2 a giallo (7) con costanti
; sprite_set_color(2, 7)
; 
; while True: # pragma: no cover
;     pass # pragma: no cover
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
    jsr sprite_enable
    jsr sprite_set_color
    jsr sprite_set_color
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; # Abilita sprite 0 e 1 (maschera 1+2=3)
; sprite_enable(3)
; 
; # Imposta la posizione dello sprite 1 a X>255
; # LSB di X = 300-256 = 44
; sprite_set_pos(1, 44, 100)
; # Imposta il bit MSB per lo sprite 1 (maschera 2)
; sprite_set_x_msb(2)
; 
; # Disabilita lo sprite 0 (maschera 1)
; sprite_disable(1)
; 
; while True: # pragma: no cover
;     pass # pragma: no cover
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
    jsr sprite_enable
    jsr sprite_set_pos
    jsr sprite_set_x_msb
    jsr sprite_disable
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; # Espande lo sprite 0 in Y e lo sprite 1 in X
; y_expand_mask = 1 # sprite 0
; x_expand_mask = 2 # sprite 1
; sprite_expand_xy(y_expand_mask, x_expand_mask)
; 
; # Espande lo sprite 2 sia in X che in Y usando costanti
; sprite_expand_xy(4, 4)
; 
; while True: # pragma: no cover
;     pass # pragma: no cover
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
    jsr sprite_expand_xy
    jsr sprite_expand_xy
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; # Imposta la posizione dello sprite 1 a X>255
; # LSB di X = 300-256 = 44
; sprite_set_pos(1, 44, 100)
; # Imposta il bit MSB per lo sprite 1 (maschera 2)
; sprite_set_x_msb(2)
; 
; # Ora cancella il bit MSB per lo sprite 1, riportando la sua X a 44
; msb_mask_to_clear = 2
; sprite_set_x_msb_clear(msb_mask_to_clear)
; 
; while True: # pragma: no cover
;     pass # pragma: no cover
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
    jsr sprite_set_pos
    jsr sprite_set_x_msb
    jsr sprite_set_x_msb_clear
rts ; End of main program
; Generated by py2c64 compiler
; --- Python Source Code ---
; # Set pointer for sprite 0 to point to data block at $3000 (pointer value $C0 = 192)
; sprite_set_pointer(0, 192)
; 
; # Set pointer for sprite 1 using variables
; s_num = 1
; ptr_val = 193 # for data at $3040
; sprite_set_pointer(s_num, ptr_val)
; 
; while True: # pragma: no cover
;     pass # pragma: no cover
; --------------------------
* = $1000
; --- Main Program and Functions ---
main:
    jsr sprite_set_pointer
    jsr sprite_set_pointer
rts ; End of main program

; --- Data Segment (Variables and Constants) ---
ptr_val .res 2
s_num .res 2
temp_0 .res 2
ptr_val * = * + 2
s_num * = * + 2
temp_0 * = * + 4

; --- Subroutines ---

; Routine: sprite_set_pointer
sprite_set_pointer
    ; Input: X=sprite_num, A=valore puntatore
    STA 2040,X
    RTS
